---
- hosts: database
  become: yes
  tasks:
    - name: create custom.facts directory
      file:
        path: /etc/ansible/facts.d
        state: directory
    - name: insert custom facts file
      copy:
        src: files/custom.fact
        dest: /etc/ansible/facts.d/custom.fact
    - name: retrieve facts 
      setup:
    - name: fail when custom facts is not retrieved
      fail:
        msg: "custom facts is not retrieved"
      when: ansible_local.custom.sample_exam is not defined
