---
- hosts: all
  tasks:
    - setup:

- hosts: database
  become: yes
  gather_facts: yes
  tasks:
    - name: uses a Jinja2 template server_list.j2 to create a file /etc/server_list.txt
      template:
        src: templates/server_list.txt.j2
        dest: /etc/server_list.txt
        owner: automation
        group: automation
        mode: 0600
        setype: net_conf_t
