---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: update vm.swappiness to 10 when a server has more than 2048MB of RAM
      sysctl:
        name: vm.swappiness
        value: 10
        state: present
        reloaded: yes
      when: ansible_memory_mb.real.total > 2048
    - name: show error message when server has less than 2048MB of RAM
      fail:
        msg: "Server memory less than 2048MB"
      when: ansible_memory_mb.real.total < 2048
