---
# tasks file for sample-mysql
- name: primary partition number 1 of size 800MB on device /dev/sdb is created
  parted:
    device: /dev/nvme1n1 
    number: 1
    state: present
    part_end: 400MB
- name: An LVM volume group called vg_database is created that uses the primary partition created above
  lvg:
    vg: vg_database
    pvs: /dev/nvme1n1
    state: present
    force: yes
- name: An LVM logical volume called lv_mysql is created of size 512MB in the volume group vg_database
  lvol:
    lv: lv_mysql
    vg: vg_database
    size: 256
    force: yes
- name: An XFS filesystem on the logical volume lv_mysql is created
  filesystem:
    dev: /dev/vg_database/lv_mysql
    fstype: xfs
- name: Logical volume lv_mysql is permanently mounted on /mnt/mysql_backups
  mount:
    path: /mnt/mysql_backups
    fstype: xfs
    state: mounted
    src: /dev/vg_database/lv_mysql
- name: mysql-community-server package is installed
  yum:
    name: mysql-community-server
    state: present
- name: Firewall is configured to allow all incoming traffic on MySQL port TCP 3306
  firewalld:
    port: 3306/tcp
    zone: public
    state: enabled
    permanent: yes
    immediate: yes
- name: install MySQL-python module
  yum:
    name: MySQL-python
    state: present
- name: enable and start mysql-server
  service:
    name: mysqld
    enabled: yes
    state: started
- name: MySQL server configuration file is generated from the my.cnf.j2 Jinja2 template with the following content
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
- name: include database_password vars
  include_vars: /Users/LamineBA/Documents/workspace/aws/ansible/linuxacademy/exam-lisenet/secret.yml
- name: MySQL root user password should be set from the variable database_password
  mysql_user:
    name: root
    password: "{{ database_password }}"
    priv: '*.*:ALL'
    state: present 
